# Generated by Django 2.0.4 on 2018-04-24 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='Dhaka', max_length=200)),
                ('sub_district', models.CharField(default='Dhaka', max_length=200)),
                ('city', models.CharField(default='Dhaka', max_length=200)),
                ('zip', models.IntegerField(default=1000)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='Authentication.Address')),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent', to='Authentication.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=200)),
                ('chassis_no', models.CharField(max_length=200)),
                ('journey_date', models.DateField(default=datetime.date.today, null=True)),
                ('capacity', models.FloatField(default=0.0)),
                ('model', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('driver_code_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_code', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
