# Generated by Django 2.0.4 on 2018-04-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sub_distict',
            new_name='sub_district',
        ),
    ]
