# Generated by Django 2.0.4 on 2018-04-08 10:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20180408_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=880, max_length=128),
        ),
    ]
