# Generated by Django 2.0.4 on 2018-04-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_trackvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackvehicle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='Authentication.Vehicle'),
        ),
    ]
