# Generated by Django 2.0.4 on 2018-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20180428_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackvehicle',
            old_name='user',
            new_name='driver',
        ),
    ]
