# Generated by Django 2.0.4 on 2018-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20180408_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
