# Generated by Django 2.0.4 on 2018-04-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20180428_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackvehicle',
            name='driver',
        ),
        migrations.AddField(
            model_name='trackvehicle',
            name='this_vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_vehicle', to='Authentication.Vehicle'),
        ),
    ]
