# Generated by Django 2.0.4 on 2018-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20180428_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackvehicle',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
