# Generated by Django 2.0.4 on 2018-04-16 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0005_auto_20180408_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='start_price',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
