# Generated by Django 2.0.4 on 2018-05-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_trackvehicle_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, null=True)),
                ('middle_place', models.CharField(max_length=200, null=True)),
                ('start_place', models.CharField(max_length=200, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='Authentication.Vehicle')),
            ],
        ),
    ]
