# Generated by Django 2.0.4 on 2018-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20180417_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='journey_date',
            field=models.DateField(),
        ),
    ]
