# Generated by Django 2.0.4 on 2018-04-19 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0008_auto_20180417_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_code_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='journey_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
